### ISSUE TITLE
Estamos offline

### ISSUE THREAD

**Issue by son0p** [daquina-io/visualizacion_apariciones_proyectos_musicales#15]
sale este mensaje "This Application Is Currently Unavailable.
Please Check Back Again Later.
Are you the account owner? Login to see your account’s usage data or upgrade to a plan with a higher limit." 

¿Cómo podemos saber cuanto estamos consumiendo?

**Comment by brolin** [comment]
Cuando entro al panel aparece este mensaje. Account is suspended until Mar
2, 2016 1:54:04 PM due to "exceeded usage hours".
All of your applications will be unavailable until then, or you can upgrade
https://www.shinyapps.io/admin/#/account/billing your account.

Parece que sobrepasamos el límite de 33 horas.

Los planes valen como U$100 al año. Hay mirar la posibilidad de instalar la
aplicación en webfaction :S

**Comment by brolin** [comment]
Ya estamos online nuevamente
